[package]
name = "databend-base"
version = "0.2.1"
edition = "2024"

[dependencies]
log = "0.4"
pin-project-lite = "0.2"

[dev-dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
