# Line width
max_width     = 100
comment_width = 100
chain_width   = 100

# Imports
reorder_imports     = true
imports_granularity = "Item"
group_imports       = "StdExternalCrate"

# Formatting
where_single_line       = true
trailing_comma          = "Vertical"
overflow_delimited_expr = true
wrap_comments           = true
inline_attribute_width  = 0
merge_derives           = false
